use fasttree

diff --git a/kmacompare b/kmacompare
--- a/kmacompare
+++ b/kmacompare
@@ -57,7 +57,7 @@ rm $TARGET_DIR/input/$curr_dir_name
 cp -r ../$curr_dir_name $TARGET_DIR/input/ &
 
 echo " calling gwf workflow..."
-gwf -b slurm -f /project/ClinicalMicrobio/faststorage/compare/workflow.py status || [echo "${red}error in gwf. ${reset}exiting." && exit 1]
+gwf -b slurm -f /project/ClinicalMicrobio/faststorage/compare/workflow.py status #|| [echo "${red}error in gwf. ${reset}exiting." && exit 1]
 
         
 
@@ -69,7 +69,7 @@ if [[ $REPLY =~ ^[Yy]$ ]]
 then
     # If the user agrees, run the workflow
     echo "submitting jobs..."
-    gwf -b slurm -f /project/ClinicalMicrobio/faststorage/compare/workflow.py run || [echo "${red}error in gwf. ${reset}exiting." && exit 1]
+    gwf -b slurm -f /project/ClinicalMicrobio/faststorage/compare/workflow.py run #|| [echo "${red}error in gwf. ${reset}exiting." && exit 1]
 
     echo ""
     echo "The job list has been submitted."
